version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    timezone: Etc/UCT
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
